---
title: "Analysis"
author: "Hjalte Mann"
date: "25/11/2021"
output: html_document
---
---
title: "IndividualPhenology"
author: "Hjalte Mann"
date: "2/2/2021"
output: html_document
---


```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(stringr)
library(GGally)
library(plotly)
knitr::opts_chunk$set(echo = TRUE)
```


Import ground truth tracked data

```{r}
thul01 = read.csv("../../data/annotations/2020_05_15_NorwayAnnotations_THUL-01_IndividualAnnotations_FRCNN.csv", header = F)

colnames(thul01) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

thul01 = thul01 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))


nars04 = read.csv("../../data/annotations/2020_05_17_NorwayAnnotations_NARS-04_IndividualAnnotations_FRCNN.csv", header = F)

colnames(nars04) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nars04 = nars04 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))


nars13 = read.csv("../../data/annotations/2020_04_30_NorwayAnnotations_NARS-13_IndividualAnnotations_FRCNN.csv", header = F)

colnames(nars13) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nars13 = nars13 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))



nyaa04 = read.csv("../../data/annotations/2020_05_23_NorwayAnnotations_Nyaa-04_IndividualAnnotations_FRCNN.csv", header = F)

colnames(nyaa04) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nyaa04 = nyaa04 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))

```

Import metadata for the 1-h subsets

```{r}

meta_2018 = read.csv("../../data/annotations/DetectionPhenology_2018_Meta_Clean_Prepped.csv")

thul01_meta = merge(thul01, meta_2018, by.x = "FileName")

thul01_meta$time = thul01_meta$DOY + (thul01_meta$Hour/24)

thul01_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
thul01_meta = thul01_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


thul01_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  

nars04_meta = merge(nars04, meta_2018, by.x = "FileName")

nars04_meta$time = nars04_meta$DOY + (nars04_meta$Hour/24)

nars04_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
nars04_meta = nars04_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


nars04_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  


meta_2019 = read.csv("../../data/annotations/DetectionPhenology_2019_Meta_Clean_Prepped.csv")


nars13_meta = merge(nars13, meta_2019, by.x = "FileName")

nars13_meta$time = nars13_meta$DOY + (nars13_meta$Hour/24)

nars13_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
nars13_meta = nars13_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


nars13_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  

```


```{r}
thul01$x_c = (thul01$x_min + thul01$x_max) / 2
thul01$y_c = (thul01$y_min + thul01$y_max) / 2

thul01 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = Class)) + 
  xlim(0,6080) +
  ylim(0,3420)


nyaa04$x_c = (nyaa04$x_min + nyaa04$x_max) / 2
nyaa04$y_c = (nyaa04$y_min + nyaa04$y_max) / 2

nyaa04 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = Class), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  theme(legend.position = "none")


```


```{r}
tracksThul01 = read.csv('../../trackResults4.csv',stringsAsFactors = FALSE)

tracksThul01$x_c = as.numeric(tracksThul01$x_C)

tracksThul01 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(objectID))) + 
  xlim(0,6080) +
  ylim(0,3420)
```


```{r}

nyaa04_meta = merge(nyaa04, meta_2019, by.x = "FileName")

nyaa04_meta$time = nyaa04_meta$DOY + (nyaa04_meta$Hour/24)

nyaa04_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
nyaa04_meta = nyaa04_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


nyaa04_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  

```

```{r}

all = bind_rows(thul01_meta[,c("flower_start","flower_length", "CameraID")], nars04_meta[,c("flower_start","flower_length", "CameraID")], nars13_meta[,c("flower_start","flower_length", "CameraID")], nyaa04_meta[,c("flower_start","flower_length", "CameraID")])

all %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length, colour = CameraID)) +
geom_smooth(aes(x = flower_start, y = flower_length), method=lm)
 
t.test(nyaa04_meta$flower_length, nars13_meta$flower_length)

```

```{r}
all %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length, colour = CameraID))
```


```{r}
d = read.csv("U:/BITCue/Projekter/TrackingFlowers/code/7temptest_eval.csv")


d %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")
```


```{r}
d1 = read.csv("U:/BITCue/Projekter/TrackingFlowers/code/8temptest_eval_THUL01.csv")


d1 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")

```



# parameterTest_3

## NYAA 04

```{r}
d1 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_NYAA-04_Evaluate.csv")


d1 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Parameter combination") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


d1 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Ten Lowest Mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


```
```{r}
# NYAA-04 gt:
nyaa04_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2021_12_13_NorwayAnnotations_NYAA-04_IndividualAnnotations_FRCNN_Metrics.csv")

length(unique(nyaa04_gt$id_gt))

```
```{r}
# Minimum mm: 10,300,60-70,29,0.9835414,38
# All zero: 0,0,0,68,0.9614075,31
# Correct noo with minimum mm:  70-160,800-1000,10,36,0.9795687,21

minmm = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NYAA-04_3/parameterTest_NYAA-04_maxDisap_10_runMean_60_maxDist_300.csv")

allzero = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NYAA-04_3/parameterTest_NYAA-04_maxDisap_0_runMean_0_maxDist_0.csv")

cornoo = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NYAA-04_3/parameterTest_NYAA-04_maxDisap_70_runMean_10_maxDist_800.csv")

```



## THUL 01

```{r}
d2 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_THUL-01_Evaluate.csv")


d2 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("THUL-01 Parameter combination") +
  facet_wrap(vars(as.factor(maxDist)))


d2 %>% 
  arrange(mm, ascending = T) %>% 
  filter(mm == 0) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm)) + 
  ggtitle("THUL-01 All zero mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


```
```{r}
# NYAA-04 gt:
thul01_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_05_15_NorwayAnnotations_THUL-01_IndividualAnnotations_FRCNN_Metrics.csv")

length(unique(thul01_gt$id_gt))

```
```{r}
# Minimum mm: 0-160, 0 + 200-1000, 10, 0, 1, 6
# All zero: 0, 0, 0, 8, 0.9885551, 6
# Correct noo with minimum mm: 0-160, 0 + 200-1000, 10, 0, 1, 6

minmm = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_THUL-01_3/parameterTest_THUL-01_maxDisap_0_runMean_10_maxDist_0.csv")

allzero = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_THUL-01_3/parameterTest_THUL-01_maxDisap_0_runMean_0_maxDist_0.csv")

cornoo = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_THUL-01_3/parameterTest_THUL-01_maxDisap_0_runMean_10_maxDist_0.csv")

```





## NARS-04

```{r}
d3 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_NARS-04_Evaluate.csv")


d3 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NARS-04 Parameter combination") +
  facet_wrap(vars(as.factor(maxDist))) +
  scale_color_gradient(low="blue", high="red")


d3 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm)) + 
  ggtitle("NARS-04 Ten lowest mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


```
```{r}
# NYAA-04 gt:
NARS04_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_05_17_NorwayAnnotations_NARS-04_IndividualAnnotations_FRCNN_Metrics.csv")

length(unique(NARS04_gt$id_gt))

```

```{r}
# Minimum mm: 10, 500, 10, 20, 0.9883991, 32
# All zero: 0, 0, 0, 85, 0.9506961, 31
# Correct noo with minimum mm: 10, 500, 10, 20, 0.9883991, 32

minmm = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_10_runMean_10_maxDist_500.csv")

allzero = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_0_runMean_0_maxDist_0.csv")

cornoo = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_10_runMean_10_maxDist_500.csv")

```




## NARS-13

```{r}
d3 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_NARS-04_Evaluate.csv")


d3 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NARS-04 Parameter combination") +
  facet_wrap(vars(as.factor(maxDist))) +
  scale_color_gradient(low="blue", high="red")


d3 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm)) + 
  ggtitle("NARS-04 Ten lowest mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


```
```{r}
# NYAA-04 gt:
NARS04_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_05_17_NorwayAnnotations_NARS-04_IndividualAnnotations_FRCNN_Metrics.csv")

length(unique(NARS04_gt$id_gt))

```

```{r}
# Minimum mm: 10, 500, 10, 20, 0.9883991, 32
# All zero: 0, 0, 0, 85, 0.9506961, 31
# Correct noo with minimum mm: 10, 500, 10, 20, 0.9883991, 32

minmm = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_10_runMean_10_maxDist_500.csv")

allzero = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_0_runMean_0_maxDist_0.csv")

cornoo = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_10_runMean_10_maxDist_500.csv")

```


