---
title: "flowerLifespanAndTemperature"
author: "Hjalte Mann"
date: '2022-06-10'
output: html_document
---





```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(stringr)
library(GGally)
library(plotly)
knitr::opts_chunk$set(echo = TRUE)
```


Import ground truth tracked data

```{r}
thul01 = read.csv("../../data/annotations/2020_05_15_NorwayAnnotations_THUL-01_IndividualAnnotations_FRCNN_Metrics.csv", header = T)

colnames(thul01) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

thul01 = thul01 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))


nars04 = read.csv("../../data/annotations/2020_05_17_NorwayAnnotations_NARS-04_IndividualAnnotations_FRCNN.csv", header = F)

colnames(nars04) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nars04 = nars04 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))


nars13 = read.csv("../../data/annotations/2020_04_30_NorwayAnnotations_NARS-13_IndividualAnnotations_FRCNN.csv", header = F)

colnames(nars13) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nars13 = nars13 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))



nyaa04 = read.csv("../../data/annotations/2021_12_13_NorwayAnnotations_NYAA-04_IndividualAnnotations_FRCNN_Metrics.csv", header = T)

colnames(nyaa04) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nyaa04 = nyaa04 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))



nars17 = read.csv("../../data/annotations/2021_12_30_NorwayAnnotations_NARS-17_IndividualAnnotations_FRCNN_Metrics.csv", header = T)

colnames(nars17) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nars17 = nars17 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))



```

Import metadata for the 1-h subsets

```{r}

meta_2018 = read.csv("../../data/annotations/DetectionPhenology_2018_Meta_Clean_Prepped.csv")

thul01_meta = merge(thul01, meta_2018, by.x = "FileName")

thul01_meta$time = thul01_meta$DOY + (thul01_meta$Hour/24)

thul01_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
thul01_meta = thul01_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


thul01_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  

nars04_meta = merge(nars04, meta_2018, by.x = "FileName")

nars04_meta$time = nars04_meta$DOY + (nars04_meta$Hour/24)

nars04_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
nars04_meta = nars04_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


nars04_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  


meta_2019 = read.csv("../../data/annotations/DetectionPhenology_2019_Meta_Clean_Prepped.csv")


nars13_meta = merge(nars13, meta_2019, by.x = "FileName")
nars13_meta$time = nars13_meta$DOY + (nars13_meta$Hour/24)
nars13_meta %>% 

ggplot()+
  geom_point(aes(x = time, y = Class))

nars13_meta = nars13_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))

nars13_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  



nars17_meta = merge(nars17, meta_2019, by.x = "FileName")
nars17_meta$time = nars17_meta$DOY + (nars17_meta$Hour/24)

nars17_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))

nars17_meta = nars17_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))

nars17_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))


```


```{r}
thul01$x_c = (thul01$x_min + thul01$x_max) / 2
thul01$y_c = (thul01$y_min + thul01$y_max) / 2

thul01 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = Class)) + 
  xlim(0,6080) +
  ylim(0,3420)


nyaa04$x_c = (nyaa04$x_min + nyaa04$x_max) / 2
nyaa04$y_c = (nyaa04$y_min + nyaa04$y_max) / 2

nyaa04 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = Class), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  theme(legend.position = "none")



nars17$x_c = (nars17$x_min + nars17$x_max) / 2
nars17$y_c = (nars17$y_min + nars17$y_max) / 2

nars17 %>% 
  ggplot() +
  geom_jitter(aes(x = x_c, y = y_c, color = Class), size = 5) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  theme(legend.position = "none")



nars13$x_c = (nars13$x_min + nars13$x_max) / 2
nars13$y_c = (nars13$y_min + nars13$y_max) / 2

nars13 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = Class), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  theme(legend.position = "none")


nars04$x_c = (nars04$x_min + nars04$x_max) / 2
nars04$y_c = (nars04$y_min + nars04$y_max) / 2


```



```{r}

nyaa04_meta = merge(nyaa04, meta_2019, by.x = "FileName")

nyaa04_meta$time = nyaa04_meta$DOY + (nyaa04_meta$Hour/24)

nyaa04_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
nyaa04_meta = nyaa04_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


nyaa04_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length, colour = Class))
  

```

```{r}
all = bind_rows(
thul01_meta[,c("FileName", "flower_start","flower_length", "CameraID", "Temperature", "DOY", "Class")],     nars04_meta[,c("FileName", "flower_start","flower_length", "CameraID", "Temperature", "DOY", "Class")], nars13_meta[,c("FileName", "flower_start","flower_length", "CameraID", "Temperature", "DOY", "Class")], nyaa04_meta[,c("FileName", "flower_start","flower_length", "CameraID", "Temperature", "DOY", "Class")], nars17_meta[,c("FileName", "flower_start","flower_length", "CameraID", "Temperature", "DOY", "Class")])

allT = all %>% 
  distinct(FileName, .keep_all = T) %>% 
  group_by(CameraID, DOY) %>%
  mutate(minT = min(Temperature), maxT = max(Temperature))

allT = allT %>% 
  group_by(CameraID, DOY) %>% 
  mutate(meanDailyT = (minT + maxT)/2)

allT = allT %>% 
  group_by(CameraID, Class) %>% 
  mutate(meanT = mean(meanDailyT))


allT %>% 
  distinct(Class, .keep_all = T) %>% 
  ggplot() + 
  geom_boxplot(aes(x = meanT, y = flower_length, colour = CameraID))

allT %>% 
  distinct(Class, .keep_all = T) %>% 
  ggplot() + 
  geom_point(aes(x = meanT, y = flower_length, colour = CameraID))



allT %>% 
  distinct(Class, .keep_all = T) %>% 
  ggplot() + 
  geom_boxplot(aes(x = flower_start, y = meanT, colour = CameraID))


```


```{r}
all = all %>% 
  mutate("camCode" = case_when(CameraID == "THUL-01"~ "2018 THUL B", CameraID == "NARS-04"~ "2018 NARS A", CameraID == "NARS-13"~ "2019 NARS C", CameraID == "NARS-17"~ "2019 NARS D", CameraID == "NYALE-04"~ "2019 NYAA E"))

axisSize = 30
legendTitleSize = 30
legendTextSize = 28
  
f1 = all %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length, fill = camCode, shape = camCode), size = 8) + 
  xlab("Onset of flowering (DOY)") + 
  ylab("Number of days flowering") +
    theme_bw()  +
  scale_fill_manual(name = "Camera ID",
                      values = c("gray26", "brown3", "dodgerblue3", "darkorange2", "chartreuse3"), aesthetics = c("colour", "fill")) + 
  scale_shape_manual(name = "Camera ID",
                      values = c(21,22,23,24,25)) + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.title = element_text(size = legendTitleSize),
        text = element_text(size = axisSize),
        legend.text = element_text(size = legendTextSize),
        axis.line = element_line(),
        axis.text=element_text(colour="black"),
        panel.spacing = unit(0.7, "lines"))

f1

#ggsave("U:/BITCue/Projekter/TrackingFlowers/figures/OnsetVSLength.png", f1, width = 15, height = 10)
 


```