---
title: "Analysis"
author: "Hjalte Mann"
date: "25/11/2021"
output: html_document
---
---
title: "IndividualPhenology"
author: "Hjalte Mann"
date: "2/2/2021"
output: html_document
---


```{r setup, include=FALSE}

library(ggplot2)
library(dplyr)
library(stringr)
library(plotly)
library(GGally)

knitr::opts_chunk$set(echo = TRUE)
```


Import ground truth tracked data

```{r}
thul01 = read.csv("../../data/annotations/2020_05_15_NorwayAnnotations_THUL-01_IndividualAnnotations_FRCNN_Metrics.csv", header = T)

colnames(thul01) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

thul01 = thul01 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))


nars04 = read.csv("../../data/annotations/2020_05_17_NorwayAnnotations_NARS-04_IndividualAnnotations_FRCNN.csv", header = F)

colnames(nars04) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nars04 = nars04 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))


nars13 = read.csv("../../data/annotations/2020_04_30_NorwayAnnotations_NARS-13_IndividualAnnotations_FRCNN.csv", header = F)

colnames(nars13) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nars13 = nars13 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))



nyaa04 = read.csv("../../data/annotations/2021_12_13_NorwayAnnotations_NYAA-04_IndividualAnnotations_FRCNN_Metrics.csv", header = T)

colnames(nyaa04) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nyaa04 = nyaa04 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))



nars17 = read.csv("../../data/annotations/2021_12_30_NorwayAnnotations_NARS-17_IndividualAnnotations_FRCNN_Metrics.csv", header = T)

colnames(nars17) = c("FileName", "x_min", "y_min", "x_max", "y_max", "Class")

nars17 = nars17 %>%
  mutate(FileName = str_extract(FileName, regex("[A-Z]{4,5}-\\d{0,3}_\\d{6}.JPG")))



```

Import metadata for the 1-h subsets

```{r}

meta_2018 = read.csv("../../data/annotations/DetectionPhenology_2018_Meta_Clean_Prepped.csv")

thul01_meta = merge(thul01, meta_2018, by.x = "FileName")

thul01_meta$time = thul01_meta$DOY + (thul01_meta$Hour/24)

thul01_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
thul01_meta = thul01_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


thul01_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  

nars04_meta = merge(nars04, meta_2018, by.x = "FileName")

nars04_meta$time = nars04_meta$DOY + (nars04_meta$Hour/24)

nars04_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
nars04_meta = nars04_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


nars04_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  


meta_2019 = read.csv("../../data/annotations/DetectionPhenology_2019_Meta_Clean_Prepped.csv")


nars13_meta = merge(nars13, meta_2019, by.x = "FileName")
nars13_meta$time = nars13_meta$DOY + (nars13_meta$Hour/24)
nars13_meta %>% 

ggplot()+
  geom_point(aes(x = time, y = Class))

nars13_meta = nars13_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))

nars13_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))
  



nars17_meta = merge(nars17, meta_2019, by.x = "FileName")
nars17_meta$time = nars17_meta$DOY + (nars17_meta$Hour/24)

nars17_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))

nars17_meta = nars17_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))

nars17_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length))


```


```{r}
thul01$x_c = (thul01$x_min + thul01$x_max) / 2
thul01$y_c = (thul01$y_min + thul01$y_max) / 2

thul01 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = Class)) + 
  xlim(0,6080) +
  ylim(0,3420)


nyaa04$x_c = (nyaa04$x_min + nyaa04$x_max) / 2
nyaa04$y_c = (nyaa04$y_min + nyaa04$y_max) / 2

nyaa04 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = Class), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  theme(legend.position = "none")



nars17$x_c = (nars17$x_min + nars17$x_max) / 2
nars17$y_c = (nars17$y_min + nars17$y_max) / 2

nars17 %>% 
  ggplot() +
  geom_jitter(aes(x = x_c, y = y_c, color = Class), size = 5) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  theme(legend.position = "none")



nars13$x_c = (nars13$x_min + nars13$x_max) / 2
nars13$y_c = (nars13$y_min + nars13$y_max) / 2

nars13 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = Class), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  theme(legend.position = "none")


nars04$x_c = (nars04$x_min + nars04$x_max) / 2
nars04$y_c = (nars04$y_min + nars04$y_max) / 2


```



```{r}

nyaa04_meta = merge(nyaa04, meta_2019, by.x = "FileName")

nyaa04_meta$time = nyaa04_meta$DOY + (nyaa04_meta$Hour/24)

nyaa04_meta %>% 
ggplot()+
  geom_point(aes(x = time, y = Class))
  
  
nyaa04_meta = nyaa04_meta %>%
  group_by(Class) %>% 
  mutate(flower_start = min(time),
    flower_length = max(time) - min(time))


nyaa04_meta %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length, colour = Class))
  

```

```{r}

all = bind_rows(thul01_meta[,c("flower_start","flower_length", "CameraID")], nars04_meta[,c("flower_start","flower_length", "CameraID")], nars13_meta[,c("flower_start","flower_length", "CameraID")], nyaa04_meta[,c("flower_start","flower_length", "CameraID")], nars17_meta[,c("flower_start","flower_length", "CameraID")])

# Camera codes:
# 2018 NARS-04: 2018 NARS A
# 2018 THUL-01: 2018 THUL B v
# 2019 NARS-13: 2019 NARS C
# 2019 NARS-17: 2019 NARS D v
# 2019 NYAA-04: 2019 NYAA E


all = all %>% 
  mutate("camCode" = case_when(CameraID == "THUL-01"~ "2018 THUL B", CameraID == "NARS-04"~ "2018 NARS A", CameraID == "NARS-13"~ "2019 NARS C", CameraID == "NARS-17"~ "2019 NARS D", CameraID == "NYALE-04"~ "2019 NYAA E"))

axisSize = 34
legendTitleSize = 50
legendTextSize = 40
  
f1 = all %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length, fill = camCode, shape = camCode), size = 8) + 
  xlab("Onset of flowering (DOY)") + 
  ylab("Number of days flowering") +
    theme_bw()  +
  scale_fill_manual(name = "Camera ID",
                      values = c("gray26", "brown3", "dodgerblue3", "darkorange2", "chartreuse3"), aesthetics = c("colour", "fill")) + 
  scale_shape_manual(name = "Camera ID",
                      values = c(21,22,23,24,25)) + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.title = element_text(size = legendTitleSize),
        text = element_text(size = axisSize),
        legend.text = element_text(size = legendTextSize),
        axis.line = element_line(),
        axis.text=element_text(colour="black"),
        panel.spacing = unit(0.7, "lines"))

f1

#ggsave("U:/BITCue/Projekter/TrackingFlowers/figures/OnsetVSLength.png", f1, width = 15, height = 10)

#all = unique(all)

f2 = ggplot(unique(all), aes(x = camCode, y = flower_length, fill=camCode))+
  geom_boxplot() + 
  geom_point(position=position_jitterdodge()) +
  xlab("Onset of flowering (DOY)") + 
  ylab("Number of days flowering") +
  theme_bw()  +
  scale_fill_manual(name = "Camera ID", values = c("white", "white", "white", "white", "white"), aesthetics = c("colour", "fill")) + 
  
  #scale_shape_manual(name = "Camera ID",
  #scale_fill_manual(name = "Camera ID", values = c("gray26", "brown3", "dodgerblue3", "darkorange2", "chartreuse3"), aesthetics = c("colour", "fill")) + 
  
  #scale_shape_manual(name = "Camera ID",
   #                   values = c(21,22,23,24,25)) + 
  theme(legend.position = "none",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.title = element_text(size = legendTitleSize),
        text = element_text(size = axisSize),
        legend.text = element_text(size = legendTextSize),
        axis.line = element_line(),
        axis.text=element_text(colour="black"),
        panel.spacing = unit(0.7, "lines")) + 
  guides(fill = "none", color="none")

f2
ggsave("U:/BITCue/Projekter/TrackingFlowers/figures/OnsetVSLengthBox_withPoints.pdf", f2, width = 15, height = 10)




# all %>% 
# ggplot()+
#   geom_point(aes(x = flower_start, y = flower_length, colour = CameraID))# +
# #geom_smooth(aes(x = flower_start, y = flower_length), method=lm)
#  
t.test(nyaa04_meta$flower_length, nars13_meta$flower_length)

```

```{r}
all %>% 
ggplot()+
  geom_point(aes(x = flower_start, y = flower_length, colour = CameraID))
```






####### MMFIX PARAMETER TEST ########


# NYAA-04
```{r fig.height=4}
NYAA04d1 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/NYAA-04_parameterTest_Evaluation.csv")


NYAA04_p1 = NYAA04d1 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Parameter combination") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NYAA04_p2 = NYAA04d1 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Ten Lowest Mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NYAA04_p1
NYAA04_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/NYAA-04_AllCombinations.png', NYAA04_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/NYAA-04_TenLowest.png', NYAA04_p2)

rm(NYAA04_p1)
rm(NYAA04_p2)
```

# NARS-13
```{r fig.height=4}
NARS13d1 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/NARS-13_parameterTest_Evaluation.csv")


NARS13_p1 = NARS13d1 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Parameter combination") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NARS13_p2 = NARS13d1 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Ten Lowest Mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NARS13_p1
NARS13_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/NARS-13_AllCombinations.png', NARS13_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/NARS-13_TenLowest.png', NARS13_p2)

rm(NARS13_p1)
rm(NARS13_p2)
```

# NARS-04
```{r fig.height=4}
NARS04d1 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/NARS-04_parameterTest_Evaluation.csv")


NARS04_p1 = NARS04d1 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Parameter combination") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NARS04_p2 = NARS04d1 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Ten Lowest Mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NARS04_p1
NARS04_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/NARS-04_AllCombinations.png', NARS04_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/NARS-04_TenLowest.png', NARS04_p2)

rm(NARS04_p1)
rm(NARS04_p2)
```

# NARS-17
```{r fig.height=4}
NARS17d1 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/NARS-17_parameterTest_Evaluation.csv")


NARS17_p1 = NARS17d1 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Parameter combination") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NARS17_p2 = NARS17d1 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Ten Lowest Mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NARS17_p1
NARS17_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/NARS-17_AllCombinations.png', NARS17_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/NARS-17_TenLowest.png', NARS17_p2)

rm(NARS17_p1)
rm(NARS17_p2)
```

# THUL-01
```{r fig.height=4}
THUL01d1 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/THUL-01_parameterTest_Evaluation.csv")


THUL01_p1 = THUL01d1 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Parameter combination") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


THUL01_p2 = THUL01d1 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Ten Lowest Mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


THUL01_p1
THUL01_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/THUL-01_AllCombinations.png', THUL01_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/figures/THUL-01_TenLowest.png', THUL01_p2)

rm(THUL01_p1)
rm(THUL01_p2)
```



### Explore combinations

# NYAA-04
```{r echo = FALSE}
print("NYAA-04")
nyaa04_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2021_12_13_NorwayAnnotations_NYAA-04_IndividualAnnotations_FRCNN_Metrics.csv")

print('True number of flowers')
length(unique(nyaa04_gt$id_gt))

# Minimum mm
print("Lowest number of mismatches")
min(NYAA04d1$mm)
NYAA04Minmm = NYAA04d1[NYAA04d1$mm == min(NYAA04d1$mm),]

# All zero
NYAA04AllZero = NYAA04d1 %>% 
  filter(maxDisap == 0 & maxDist == 0 & runMean == 0)

# Correct number of flowers and minimum mm
NYAA04CorrectflowerMinmm = NYAA04d1 %>% 
  filter(number_of_objects == length(unique(nyaa04_gt$id_gt)))
NYAA04CorrectflowerMinmm = NYAA04CorrectflowerMinmm[NYAA04CorrectflowerMinmm$mm == min(NYAA04CorrectflowerMinmm$mm),]
```

# NARS-13
```{r echo = FALSE}
print("NARS-13")
nars13_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_04_30_NorwayAnnotations_NARS-13_IndividualAnnotations_FRCNN_Metrics.csv")

print('True number of flowers')
length(unique(nars13_gt$id_gt))

# Minimum mm
print("Lowest number of mismatches")
min(NARS13d1$mm)
NARS13Minmm = NARS13d1[NARS13d1$mm == min(NARS13d1$mm),]

# All zero
NARS13AllZero = NARS13d1 %>% 
  filter(maxDisap == 0 & maxDist == 0 & runMean == 0)

# Correct number of flowers and minimum mm
NARS13CorrectflowerMinmm = NARS13d1 %>% 
  filter(number_of_objects == length(unique(nars13_gt$id_gt)))
NARS13CorrectflowerMinmm = NARS13CorrectflowerMinmm[NARS13CorrectflowerMinmm$mm == min(NARS13CorrectflowerMinmm$mm),]
```

# NARS-04
```{r echo = FALSE}
print("NARS-04")
nars04_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_05_17_NorwayAnnotations_NARS-04_IndividualAnnotations_FRCNN_Metrics.csv")

print('True number of flowers')
length(unique(nars04_gt$id_gt))

# Minimum mm
print("Lowest number of mismatches")
min(NARS04d1$mm)
NARS04Minmm = NARS04d1[NARS04d1$mm == min(NARS04d1$mm),]

# All zero
NARS04AllZero = NARS04d1 %>% 
  filter(maxDisap == 0 & maxDist == 0 & runMean == 0)

# Correct number of flowers and minimum mm
NARS04CorrectflowerMinmm = NARS04d1 %>% 
  filter(number_of_objects == length(unique(nars04_gt$id_gt)))
NARS04CorrectflowerMinmm = NARS04CorrectflowerMinmm[NARS04CorrectflowerMinmm$mm == min(NARS04CorrectflowerMinmm$mm),]
```

# NARS-17
```{r echo = FALSE}
print("NARS-17")
nars17_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2021_12_30_NorwayAnnotations_NARS-17_IndividualAnnotations_FRCNN_Metrics.csv")

print('True number of flowers')
length(unique(nars17_gt$id_gt))

# Minimum mm
print("Lowest number of mismatches")
min(NARS17d1$mm)
NARS17Minmm = NARS17d1[NARS17d1$mm == min(NARS17d1$mm),]

# All zero
NARS17AllZero = NARS17d1 %>% 
  filter(maxDisap == 0 & maxDist == 0 & runMean == 0)

# Correct number of flowers and minimum mm
NARS17CorrectflowerMinmm = NARS17d1 %>% 
  filter(number_of_objects == length(unique(nars17_gt$id_gt)))
NARS17CorrectflowerMinmm = NARS17CorrectflowerMinmm[NARS17CorrectflowerMinmm$mm == min(NARS17CorrectflowerMinmm$mm),]
```

# THUL-01
```{r echo = FALSE}
print("THUL-01")
thul01_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_05_15_NorwayAnnotations_THUL-01_IndividualAnnotations_FRCNN_Metrics.csv")

print('True number of flowers')
length(unique(thul01_gt$id_gt))

# Minimum mm
print("Lowest number of mismatches")
min(THUL01d1$mm)
THUL01Minmm = THUL01d1[THUL01d1$mm == min(THUL01d1$mm),]

# All zero
THUL01AllZero = THUL01d1 %>% 
  filter(maxDisap == 0 & maxDist == 0 & runMean == 0)

# Correct number of flowers and minimum mm
THUL01CorrectflowerMinmm = THUL01d1 %>% 
  filter(number_of_objects == length(unique(thul01_gt$id_gt)))
THUL01CorrectflowerMinmm = THUL01CorrectflowerMinmm[THUL01CorrectflowerMinmm$mm == min(THUL01CorrectflowerMinmm$mm),]
```








####### /MMFIX PARAMETER TEST ########







# parameterTest_3

## NYAA 04

```{r fig.height=4}
d1 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_NYAA-04_Evaluate.csv")


NYAA04_p1 = d1 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Parameter combination") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NYAA04_p2 = d1 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NYAA-04 Ten Lowest Mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


NYAA04_p1
NYAA04_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/NYAA-04_AllCombinations.png', NYAA04_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/NYAA-04_TenLowest.png', NYAA04_p2)

```





```{r}
# NYAA-04 gt:
nyaa04_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2021_12_13_NorwayAnnotations_NYAA-04_IndividualAnnotations_FRCNN_Metrics.csv")

length(unique(nyaa04_gt$id_gt))

```
```{r}
# Minimum mm: 10,300,60-70,29,0.9835414,38
# All zero: 0,0,0,68,0.9614075,31
# Correct noo with minimum mm:  70-160,800-1000,10,36,0.9795687,21

nyaa04minmm = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NYAA-04_3/parameterTest_NYAA-04_maxDisap_10_runMean_60_maxDist_300.csv")

allzero = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NYAA-04_3/parameterTest_NYAA-04_maxDisap_0_runMean_0_maxDist_0.csv")

cornoo = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NYAA-04_3/parameterTest_NYAA-04_maxDisap_70_runMean_10_maxDist_800.csv")

```


```{r fig.height=4}

nyaa04minmm %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(objectID)), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("NYAA-04 Tracked (Minimum mm)") +
  theme(legend.position = "none")


nyaa04xx = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NYAA-04_3/parameterTest_NYAA-04_maxDisap_10_runMean_10_maxDist_300.csv")

nyaa04xx %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(objectID)), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("NYAA-04 Tracked (xx)")  +
  theme(legend.position = "none")



nyaa04 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(Class)), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("NYAA-04 Ground Truth") +
  theme(legend.position = "none")




#nyaa04_meta %>% 
#  ggplot() +
#  geom_point(aes(x = DOY, y = Class))


```


## THUL 01

# After MMFix
```{r fig.height=4}
d2 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/MMFix/THUL-01_parameterTest_Evaluation.csv")


THUL01_p1 = d2 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("THUL-01 Parameter combination") +
  facet_wrap(vars(as.factor(maxDist)))

THUL01_p2 = d2 %>% 
  arrange(mm, ascending = T) %>% 
  filter(mm == 0) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm)) + 
  ggtitle("THUL-01 All zero mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")


THUL01_p1
THUL01_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/THUL-01_AllCombinations.png', THUL01_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/THUL-01_AllZero.png', THUL01_p2)
```

```{r fig.height=4}
# d2 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_THUL-01_Evaluate.csv")
# 
# 
# THUL01_p1 = d2 %>% 
#   ggplot() +
#   geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
#   ggtitle("THUL-01 Parameter combination") +
#   facet_wrap(vars(as.factor(maxDist)))
# 
# 
# THUL01_p2 = d2 %>% 
#   arrange(mm, ascending = T) %>% 
#   filter(mm == 0) %>% 
#   ggplot() +
#   geom_point(aes(x=runMean, y = maxDisap, size = mm)) + 
#   ggtitle("THUL-01 All zero mismatches") +
#   facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")
# 
# 
# THUL01_p1
# THUL01_p2
# 
# ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/THUL-01_AllCombinations.png', THUL01_p1)
# ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/THUL-01_AllZero.png', THUL01_p2)
```

```{r}
# THUL-01 gt:
thul01_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_05_15_NorwayAnnotations_THUL-01_IndividualAnnotations_FRCNN_Metrics.csv")

length(unique(thul01_gt$id_gt))

```

```{r}
# Minimum mm: 0-160, 0 + 200-1000, 10, 0, 1, 6
# All zero: 0, 0, 0, 8, 0.9885551, 6
# Correct noo with minimum mm: 0-160, 0 + 200-1000, 10, 0, 1, 6

minmm = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_THUL-01_3/parameterTest_THUL-01_maxDisap_0_runMean_10_maxDist_0.csv")

allzero = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_THUL-01_3/parameterTest_THUL-01_maxDisap_0_runMean_0_maxDist_0.csv")

cornoo = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_THUL-01_3/parameterTest_THUL-01_maxDisap_0_runMean_10_maxDist_0.csv")

```

```{r fig.height=4}

cornoo %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(objectID)), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("THUL-01 Tracked") +
  theme(legend.position = "none")



thul01 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(Class)), size = 1, shape = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("THUL-01 Ground Truth") +
  theme(legend.position = "none")
```




## NARS-04

```{r fig.height=4}

d3 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_NARS-04_Evaluate.csv")


NARS04_p1 = d3 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NARS-04 Parameter combination") +
  facet_wrap(vars(as.factor(maxDist))) +
  scale_color_gradient(low="blue", high="red")


NARS04_p2 = d3 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm)) + 
  ggtitle("NARS-04 Ten lowest mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")

NARS04_p1
NARS04_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/NARS-04_AllCombinations.png', NARS04_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/NARS-04_TenLowest.png', NARS04_p2)
```



```{r}
# NARS-04 gt:
NARS04_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_05_17_NorwayAnnotations_NARS-04_IndividualAnnotations_FRCNN_Metrics.csv")

length(unique(NARS04_gt$id_gt))

```

```{r}
# Minimum mm: 10, 500, 10, 20, 0.9883991, 32
# All zero: 0, 0, 0, 85, 0.9506961, 31
# Correct noo with minimum mm: 10, 500, 10, 20, 0.9883991, 32

nars04minmm = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_10_runMean_10_maxDist_500.csv")

allzero = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_0_runMean_0_maxDist_0.csv")

cornoo = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-04_3/parameterTest_NARS-04_maxDisap_10_runMean_10_maxDist_500.csv")

```


```{r fig.height=4}

nars04minmm %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(objectID)), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("NARS-04 Tracked") +
  theme(legend.position = "none")



nars04 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(Class)), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("NARS-04 Ground Truth") +
  theme(legend.position = "none")
```



## NARS-13

```{r}
d4 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_NARS-13_Evaluate.csv")


NARS04_p1 = d4 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NARS-13 Parameter combination") +
  facet_wrap(vars(as.factor(maxDist))) +
  scale_color_gradient(low="blue", high="red")


NARS04_p2 = d4 %>% 
  arrange(mm, ascending = T) %>% 
  slice_head(n = 10) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm)) + 
  ggtitle("NARS-13 Ten lowest mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")

NARS04_p1
NARS04_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/NARS-13_AllCombinations.png', NARS04_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/NARS-13_TenLowest.png', NARS04_p2)


```




```{r}
d5 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/parameterTest_3_NARS-17_Evaluate.csv")


NARS17_p1 = d5 %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm, colour = mm)) + 
  ggtitle("NARS-17 Parameter combination") +
  facet_wrap(vars(as.factor(maxDist))) +
  scale_color_gradient(low="blue", high="red")


NARS17_p2 = d5 %>% 
  arrange(mm, ascending = T) %>% 
  filter(mm == 0) %>% 
  ggplot() +
  geom_point(aes(x=runMean, y = maxDisap, size = mm)) + 
  ggtitle("NARS-17 All zero mismatches") +
  facet_wrap(vars(maxDist))+scale_color_gradient(low="blue", high="red")

NARS17_p1
NARS17_p2

#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/NARS-17_AllCombinations.png', NARS17_p1)
#ggsave('U:/BITCue/Projekter/TrackingFlowers/testResults/figures/NARS-17_TenLowest.png', NARS17_p2)


```

```{r}
# NARS-13 gt:
NARS13_gt = read.csv("U:/BITCue/Projekter/TrackingFlowers/data/annotations/2020_04_30_NorwayAnnotations_NARS-13_IndividualAnnotations_FRCNN_Metrics.csv")

length(unique(NARS13_gt$id_gt))

```

```{r}
# Minimum mm: 10-20, 300-400, 10, 78, 0.9840393, 81+85+93+97
# All zero: 0, 0, 0, 267, 0.9453653, 88
# Correct noo with minimum mm: 10, 400, 10, 78, 0.9840393, 85

nars13minmm = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-13_3/parameterTest_NARS-13_maxDisap_0_runMean_0_maxDist_0.csv")

allzero = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-13_3/parameterTest_NARS-13_maxDisap_0_runMean_0_maxDist_0.csv")

cornoo = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/_parameterTest_NARS-13_3/parameterTest_NARS-13_maxDisap_10_runMean_10_maxDist_0.csv")

```

```{r fig.height=4}

nars13minmm %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(objectID)), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("NARS-13 Tracked (Minimum mm)") +
  theme(legend.position = "none")



nars13 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, color = as.factor(Class)), size = 1) + 
  xlim(0,6080) +
  ylim(0,3420) + 
  ggtitle("NARS-13 Ground Truth") +
  theme(legend.position = "none")


length(unique(nars13$Class))
```


```{r}
tempNARS04 = read.csv("U:/BITCue/Projekter/TrackingFlowers/testResults/tempNARS04.csv")


tempNARS04 %>% 
  filter(x_c > 1100 & x_c < 1110) %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, colour = as.factor(objectID))) + 
  xlim(1100,1110) + 
  ylim(2250,2320)


tempNARS04 %>% 
  ggplot() +
  geom_point(aes(x = x_c, y = y_c, colour = as.factor(objectID)), size = 0.5) 

```
Largest gap in time

```{r}
x = nyaa04_meta %>%
    group_by(Class) %>%
    arrange(time) %>%
    mutate(diff = time - lag(time, default = first(time)))

x = nars13_meta %>%
    group_by(Class) %>%
    arrange(time) %>%
    mutate(diff = time - lag(time, default = first(time)))






# NYAA-04: 5.1
# NARS-13: 1.25


```




Largest gap in number of frames

```{r}

x = nyaa04 %>% 
  mutate(frame = as.integer(str_remove(str_extract(FileName, regex("\\d{6}")), "^0+"))) %>% 
  group_by(Class) %>%
  arrange(frame) %>%
  mutate(diff = frame - lag(frame, default = first(frame)))


```

